/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get exchange rates
         * @description Returns exchange rates blended across providers. Without date params, returns the latest rates. Each record is a single currency pair.
         */
        get: operations["getRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rate/{base}/{quote}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single exchange rate pair
         * @description Returns the blended exchange rate for a single currency pair. Without a date param, returns the latest rate.
         */
        get: operations["getRate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/currency/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single currency
         * @description Returns details for a single currency, including provider information or peg metadata.
         */
        get: operations["getCurrency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available currencies
         * @description Returns available currencies with their names and date ranges. By default, only active currencies are included.
         */
        get: operations["getCurrencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available data providers
         * @description Returns available exchange rate data providers with their base currency.
         */
        get: operations["getProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Rate: {
            /**
             * Format: date
             * @description The date of the rate
             */
            date: string;
            /** @description Base currency code */
            base: string;
            /** @description Quote currency code */
            quote: string;
            /** @description Exchange rate value */
            rate: number;
            /** @description Per-provider rates for this pair. Present only when `expand=providers` is set. Each entry has the provider's published rate (rebased to the row's base). Entries with `excluded: true` did not contribute to the blended `rate` — either flagged as outliers by the consensus filter, or overridden by a currency peg. Omitted on synthesized peg rows where no provider published the quote. */
            providers?: {
                /** @description Provider key */
                key: string;
                /** @description Provider's rate, rebased to the row's base */
                rate: number;
                /** @description Present and true when this entry did not contribute to the blended rate */
                excluded?: boolean;
            }[];
        };
        Currency: {
            /** @description ISO 4217 currency code */
            iso_code: string;
            /** @description ISO 4217 numeric code */
            iso_numeric?: string | null;
            /** @description Full currency name */
            name: string;
            /** @description Currency symbol */
            symbol?: string | null;
            /**
             * Format: date
             * @description Earliest available date
             */
            start_date?: string | null;
            /**
             * Format: date
             * @description Latest available date
             */
            end_date?: string | null;
        };
        CurrencyDetail: {
            /** @description ISO 4217 currency code */
            iso_code: string;
            /** @description ISO 4217 numeric code */
            iso_numeric?: string | null;
            /** @description Full currency name */
            name: string;
            /** @description Currency symbol */
            symbol?: string | null;
            /** @description Provider keys that publish this currency */
            providers?: string[];
            /** @description Peg metadata, present only for pegged currencies */
            peg?: {
                base?: string;
                rate?: number;
                authority?: string;
                /** Format: uri */
                source?: string;
            };
        };
        Provider: {
            /** @description Provider identifier */
            key: string;
            /** @description Full provider name */
            name: string;
            /** @description ISO 3166-1 alpha-2 country code */
            country_code?: string | null;
            /** @description Official rate type as used by the source */
            rate_type?: string | null;
            /** @description Base currency for published rates */
            pivot_currency?: string | null;
            /**
             * Format: uri
             * @description Link to the data source
             */
            data_url?: string | null;
            /**
             * Format: uri
             * @description Link to terms of use
             */
            terms_url?: string | null;
            /**
             * Format: date
             * @description Earliest available date
             */
            start_date?: string | null;
            /**
             * Format: date
             * @description Latest available date
             */
            end_date?: string | null;
            /**
             * @description How often the provider publishes rates. Determines the unit of publishes_missed: a count of days, ISO weeks, or calendar months. Null for historical-only providers with no scheduled cadence.
             * @enum {string|null}
             */
            publish_cadence?: "daily" | "weekly" | "monthly" | null;
            /** @description Number of expected publishes missed since end_date, in units of publish_cadence. For daily providers, counts scheduled publish days strictly between end_date and today. For weekly and monthly providers, counts ISO weeks or calendar months between the latest imported bucket and the bucket whose publish window has already started. Null when the provider has no scheduled cadence or no imported data. */
            publishes_missed?: number | null;
            /** @description Currency codes covered by this provider */
            currencies: string[];
        };
    };
    responses: {
        /** @description Invalid request */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message?: string;
                };
            };
        };
        /** @description No data found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message?: string;
                };
            };
        };
    };
    parameters: {
        /** @description Specific date (YYYY-MM-DD). Cannot be combined with from/to. */
        date: string;
        /** @description Start of date range (YYYY-MM-DD) */
        from: string;
        /** @description End of date range (YYYY-MM-DD). Defaults to today. */
        to: string;
        /** @description Base currency (default: EUR) */
        base: string;
        /** @description Comma-separated list of quote currencies to include */
        quotes: string;
        /** @description Comma-separated list of data providers to include */
        providers: string;
        /** @description Downsample rates by time period. Only applies to date ranges. */
        group: "week" | "month";
        /** @description Comma-separated list of optional fields to include per record. Currently supports `providers`, which adds an array of `{ key, rate }` objects per record showing each provider's individual rate. Outliers excluded from the blend (and providers whose rate was overridden by a currency peg) are flagged with `excluded: true`. The field is omitted on synthesized peg rows where no provider published the quote. In CSV output, the `providers` column is encoded as `KEY:RATE` pairs joined by `|`, with a trailing `*` on excluded entries (e.g. `ECB:0.92|FED:1.50*`). */
        expand: "providers";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRates: {
        parameters: {
            query?: {
                /** @description Specific date (YYYY-MM-DD). Cannot be combined with from/to. */
                date?: components["parameters"]["date"];
                /** @description Start of date range (YYYY-MM-DD) */
                from?: components["parameters"]["from"];
                /** @description End of date range (YYYY-MM-DD). Defaults to today. */
                to?: components["parameters"]["to"];
                /** @description Base currency (default: EUR) */
                base?: components["parameters"]["base"];
                /** @description Comma-separated list of quote currencies to include */
                quotes?: components["parameters"]["quotes"];
                /** @description Comma-separated list of data providers to include */
                providers?: components["parameters"]["providers"];
                /** @description Downsample rates by time period. Only applies to date ranges. */
                group?: components["parameters"]["group"];
                /** @description Comma-separated list of optional fields to include per record. Currently supports `providers`, which adds an array of `{ key, rate }` objects per record showing each provider's individual rate. Outliers excluded from the blend (and providers whose rate was overridden by a currency peg) are flagged with `excluded: true`. The field is omitted on synthesized peg rows where no provider published the quote. In CSV output, the `providers` column is encoded as `KEY:RATE` pairs joined by `|`, with a trailing `*` on excluded entries (e.g. `ECB:0.92|FED:1.50*`). */
                expand?: components["parameters"]["expand"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exchange rates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "date": "2024-01-15",
                     *         "base": "EUR",
                     *         "quote": "USD",
                     *         "rate": 1.089
                     *       },
                     *       {
                     *         "date": "2024-01-15",
                     *         "base": "EUR",
                     *         "quote": "GBP",
                     *         "rate": 0.8623
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Rate"][];
                    /**
                     * @example { "date": "2024-01-15", "base": "EUR", "quote": "USD", "rate": 1.089 }
                     *     { "date": "2024-01-15", "base": "EUR", "quote": "GBP", "rate": 0.8623 }
                     */
                    "application/x-ndjson": string;
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getRate: {
        parameters: {
            query?: {
                /** @description Specific date (YYYY-MM-DD). Cannot be combined with from/to. */
                date?: components["parameters"]["date"];
                /** @description Comma-separated list of data providers to include */
                providers?: components["parameters"]["providers"];
            };
            header?: never;
            path: {
                base: string;
                quote: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exchange rate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "date": "2026-03-25",
                     *       "base": "EUR",
                     *       "quote": "USD",
                     *       "rate": 1.1568
                     *     }
                     */
                    "application/json": components["schemas"]["Rate"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Currency details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "iso_code": "USD",
                     *       "iso_numeric": "840",
                     *       "name": "United States Dollar",
                     *       "symbol": "$",
                     *       "providers": [
                     *         "ECB",
                     *         "BOC",
                     *         "FED"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["CurrencyDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getCurrencies: {
        parameters: {
            query?: {
                /** @description Set to 'all' to include legacy currencies */
                scope?: "all";
                /** @description Comma-separated list of data providers to include */
                providers?: components["parameters"]["providers"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available currencies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "iso_code": "EUR",
                     *         "iso_numeric": "978",
                     *         "name": "Euro",
                     *         "symbol": "€",
                     *         "start_date": "1999-01-04",
                     *         "end_date": "2026-03-17"
                     *       },
                     *       {
                     *         "iso_code": "USD",
                     *         "iso_numeric": "840",
                     *         "name": "United States Dollar",
                     *         "symbol": "$",
                     *         "start_date": "1999-01-04",
                     *         "end_date": "2026-03-17"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Currency"][];
                };
            };
        };
    };
    getProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "key": "ECB",
                     *         "name": "European Central Bank",
                     *         "country_code": "EU",
                     *         "rate_type": "reference",
                     *         "pivot_currency": "EUR",
                     *         "data_url": "https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html",
                     *         "terms_url": "https://www.ecb.europa.eu/services/using-our-site/disclaimer/html/index.en.html",
                     *         "start_date": "1999-01-04",
                     *         "end_date": "2026-03-17",
                     *         "currencies": [
                     *           "USD",
                     *           "GBP"
                     *         ]
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Provider"][];
                };
            };
        };
    };
}
